### ISSUE TITLE
Draw by 3-fold repetition ?

### ISSUE THREAD

**Issue by tissatussa** [paulrwebster/Piglet#2]
i just played a game with Piglet .. in this position Piglet 1.3.3 (compiled on Linux) made a draw by 3-fold repetition, but White was clearly winning :

![piglet-draw](https://github.com/paulrwebster/Piglet/assets/1109281/98f06e32-a23d-41cb-9bb1-8a5a882a9280)

[Event "human vs engine"]
[Site "Holland @ [https://lichess.org/CAx4DTvu/black](https://lichess.org/CAx4DTvu/black)"]
[Date "2023.12.23"]
[Round "?"]
[White "Piglet v1.3.3"]
[Black "Roelof Berkepeis"]
[Result "1/2-1/2"]

1.e4 d6 2.d4 c6 3.Nf3 Qc7 4.Nc3 e5 5.dxe5 dxe5 6.Bc4 Be7 7.Ng5 Nh6 8.O-O O-O 9.h3 Nd7 10.Be3 Qd6 11.Nf3 Qg6 12.Re1 Kh8 13.a3 Ng8 14.Qd3 Bf6 15.Qd6 Rd8 16.Qc7 Re8 17.Rad1 Bd8 18.Qd6 Qxd6 19.Rxd6 f6 20.Red1 Re7 21.Kf1 Bc7 22.R6d2 Nb6 23.Bb3 Be6 24.Bxb6 Bxb6 25.Bxe6 Rxe6 26.Na4 Rae8 27.Nxb6 axb6 28.Rd7 R6e7 29.Ke2 g6 30.Rxe7 Rxe7 31.Nd2 Kg7 32.Nc4 b5 33.Nd6 Kf8 34.Nc8 Rc7 35.Rd8+ Kg7 36.Nd6 Re7 37.Nc8 Rc7 38.Nd6 Re7 39.Nc8 Rc7 {Draw by 3-fold repetition} 1/2-1/2

**Comment by paulrwebster** [comment]
3 fold repetition routine rewritten and corrected
