### ISSUE TITLE
Illegal moves

### ISSUE THREAD

**Issue by SzotsGabor** [paulrwebster/Piglet#3]
Hello Paul,

I tried Piglet 1.3.5 under the Cute Chess GUI but it lost almost all of its games owing to illegal moves.
And here is a game I played against it under Arena:

[Event "Computer chess game under Arena 3.5.1"]
[Site "Szentendre"]
[Date "2024.03.28"]
[Round "?"]
[White "Gabor Szots"]
[Black "Piglet 1.3.5 64-bit"]
[Result "*"]
[ECO "C34"]
[Opening "KGA"]
[Time "14:08:46"]
[Variation "Schallop Defence"]
[TimeControl "90+1"]
[PlyCount "12"]

1. e4 e5 2. f4 exf4 {+0.55/8 2} 3. Nf3 Nf6 {+0.55/8 2} 4. e5 Nd5 {+0.40/8
2} 5. d4 Ke7 {+0.50/7 2} 6. c4 Nc3 {0.00/8 2} *

So I had to postpone its testing.
What can you say?

Gabor Szots
CCRL testing group

**Comment by tissatussa** [comment]
@SzotsGabor i can not reproduce this .. i compiled v1.3.5 on Linux and it seems to run fine in CuteChess (GUI), i encounter no illegal moves .. i played a few games with White, using the same time control 90+1, and when i open a game with 1.e4, Piglet plays the SAME moves every game (so far..), starting with 1...a6 !? :

[Event "human vs engine"]
[Site "Holland"]
[Date "2024.03.28"]
[Round "?"]
[White "Roelof Berkepeis"]
[Black "Piglet v1.3.5"]
[Result "*"]
[ECO "B00"]
[Opening "St. George (Baker) defense"]
[TimeControl "90+1"]

1. e4 a6 {-0.35/7 3.0s} 2. Bc4 {21s} Nf6 {-0.40/7 3.0s} 3. d3 {8.1s}
d5 {-0.25/7 3.0s} 4. exd5 {4.9s} Nxd5 {-0.25/7 3.0s} 5. Ne2 {11s}
Nc6 {-0.30/7 3.0s} 6. a4 {7.5s} Nb6 {+0.35/6 3.0s} 7. Bb3 {14s}
e5 {+0.20/6 3.0s} 8. c3 {13s} Bf5 {+0.80/6 3.0s} 9. Bc2 {2.3s}
Bc5 {+1.10/6 3.0s} 10. Ng3 {2.2s} Bg6 {+1.00/6 3.0s} 11. Qe2 {10s}
Qd5 {+0.95/5 2.0s} 12. O-O {28s} O-O {+0.70/5 2.0s} 13. Kh1 {7.8s}
Rad8 {+1.00/6 2.0s} 14. Ne4 {7.8s} Bxe4 {+1.15/6 2.0s} 15. dxe4 {2.1s}
Qc4 {+0.70/7 2.0s} *

also when letting my Piglet v1.3.5 play against other engines (using 15 minutes per game + 10 sec) no illegal moves are made.

**Comment by tissatussa** [comment]
btw. the game you supplied does not contain any illegal move ..

**Comment by SzotsGabor** [comment]
> btw. the game you supplied does not contain any illegal move ..

Yes, I know. But it made two moves (Ke7 and Nc3) which indicate it does not know where the pieces are (or what pieces).

**Comment by SzotsGabor** [comment]
Another game under Arena, this time without an external Arena book.

[Event "Computer chess game under Arena 3.5.1"]
[Site "Szentendre"]
[Date "2024.03.28"]
[Round "?"]
[White "Gabor Szots"]
[Black "Piglet 1.3.5 64-bit"]
[Result "*"]
[ECO "B00"]
[Opening "King's Pawn"]
[Time "17:53:38"]
[TimeControl "90+1"]
[PlyCount "16"]

1. e4 Nh6 {0.00/8 2} 2. d4 Rg8 {-0.60/8 2} 3. Nc3 d6 {-1.15/7 2} 4. Nf3 Nd7
{-1.10/7 2} 5. Be2 e5 {-1.00/7 2} 6. O-O Ng4 {-0.85/7 2} 7. Bg5 Be7
{-0.80/7 2} 8. Bxe7 Kxe7 {-0.70/8 2} *

When I started a new game it played 1. e4 Nh6 2. d4 Rg8 again.

**Comment by SzotsGabor** [comment]
I have compiled it myself using this command line: g++ *.cpp -O3 -std=c++20 -pthread -march=native -oPiglet_1.3.6-x64-SzG.exe

And this compile seems to work OK.

**Comment by tissatussa** [comment]
> I have compiled it myself using this command line..

to compile (on Linux) i used the makefile, but i changed g++ into g++-13
i also have the Linux asset binary but i didn't use it yet.

**Comment by SzotsGabor** [comment]
It seems the illegal moves occur only when the increment is a fraction of a second, e.g. 200 ms.

**Comment by paulrwebster** [comment]
Have changed move time representation from integer to double to allow move times of less than one second.
