### ISSUE TITLE
makefile placement

### ISSUE THREAD

**Issue by tissatussa** [paulrwebster/Piglet#4]
i managed to compile v1.3.6 on Linux and it seems to run fine in CuteChess GUI .. however, the placement of your `makefile` is illogical to me : you created a folder called `makefile` which has one file called `makefile` !? I moved that file into its parent folder (where all code files are) and then i executed `make` : it results in a valid binary of 836.3 Kb.
NOTE: i used `g++-13` by changing the concerning code line in `makefile`, although older versions might work also.

why don't you put the `makefile` next to the code files ? This is normal AFAIK.

[ i'm on Xubuntu 22.04 ]

**Comment by paulrwebster** [comment]
Thanks for the advice. I have moved the makefile next to the code.
